Repository Wanted-Pre-Onboarding-FE-Team-12/wanted-pre-onboarding-IMLAB, pull requests merged in 2022-09, with the labels that each got.

#21 feat: api 모듈화
  .DS_Store
  .gitignore
  jsconfig.json
  package-lock.json
  package.json
  src/api/index.js
  src/api/movieApi.js
  src/index.js
Labels: 기능구현, api

#23 feature: search page
  src/components/Search/index.jsx
  src/components/Search/style.js
  src/pages/Search/api/searchapi.js
  src/pages/Search/components/MovieCard.jsx
  src/pages/Search/index.jsx
  src/pages/Search/style.js
  src/utils/links.js
Labels: 기능구현, 마크업, 검색

#25 Feature/Search
  src/components/Search/index.jsx
  src/components/Search/style.js
  src/pages/Search/api/searchapi.js
  src/pages/Search/components/MovieCard.jsx
  src/pages/Search/index.jsx
  src/pages/Search/style.js
  src/utils/links.js
Labels: 기능구현, 마크업, 검색

#33 Feature/search refactoring
  README.md
  package-lock.json
  src/components/Links/style.js
  src/components/Search/index.jsx
  src/components/Search/style.js
  src/pages/Search/api/searchapi.js
  src/pages/Search/components/MovieCard.jsx
  src/pages/Search/components/MovieModal.jsx
  src/pages/Search/index.jsx
  src/pages/Search/style.js
Labels: 기능구현, 리팩토링, 검색, api

#30 Feature/home 영화 클릭 기능 구현 + 일부 코드 리팩터링
  src/pages/Home/Components/MainThumbnail.jsx
  src/pages/Home/Components/Movie.jsx
  src/pages/Home/index.jsx
Labels: 기능구현, 리팩토링, 메인페이지
